# Generated by Django 5.0.3 on 2024-03-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('flight', models.CharField(max_length=100)),
                ('flight_ddate', models.DateField()),
                ('flight_adate', models.DateField()),
                ('total_fare', models.FloatField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
