# Generated by Django 5.0.3 on 2024-03-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_barcode_ticket_qr_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='TicketQR',
        ),
    ]
